[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
strategy = "rolling"

[[services]]
name = "web"
type = "web"
plan = "starter"
numReplicas = 1
